#ifndef ao_H
#define ao_H
const char ao_source[] =#version 430
layout((location=64))uniform float m;layout((location=65))uniform float x;in vec2 v;layout((location=0))uniform vec2 f;layout((location=66))uniform float l;uint t(uint v){return v=v+2127912214+(v<<12),v=v^-949894596^v>>19,v=v+374761393+(v<<5),v=v+-744332180^v<<9,v=v+-42973499+(v<<3),v=v^-1252372727^v>>16,v;}vec3 i[12]=vec3[12](vec3(1,1,0),vec3(-1,1,0),vec3(1,-1,0),vec3(-1,-1,0),vec3(1,0,1),vec3(-1,0,1),vec3(1,0,-1),vec3(-1,0,-1),vec3(0,1,1),vec3(0,-1,1),vec3(0,1,-1),vec3(0,-1,-1));float n(uint v){return float(v%(1<<20))/float(1<<20);}float p(int v){return n(t(v));}float r(ivec2 v){return n(t(v.x+t(v.y)));}float s(ivec3 v){return n(t(v.x+t(v.y+t(v.z))));}float w(float v){int f=int(floor(v));float a=fract(v),x=s(f),n=s(f+1);return mix(x,n,a);}float d(vec2 v){ivec2 f=ivec2(floor(v));vec2 a=fract(v);float n=0,x=s(f),m=s(f+ivec2(0,1)),z=s(f+ivec2(1,0)),y=s(f+ivec2(1,1));return mix(mix(x,z,a.x),mix(m,y,a.x),a.y)*2.-1.;}float e(vec3 v){ivec3 f=ivec3(floor(v));vec3 a=fract(v);float n=0,x=s(f),m=s(f+ivec3(0,1,0)),z=s(f+ivec3(1,0,0)),y=s(f+ivec3(1,1,0)),l=s(f+ivec3(0,0,1)),i=s(f+ivec3(0,1,1)),d=s(f+ivec3(1,0,1)),w=s(f+ivec3(1,1,1));return mix(mix(mix(x,z,a.x),mix(m,y,a.x),a.y),mix(mix(l,d,a.x),mix(i,w,a.x),a.y),a.z)*2.-1.;}float c(vec2 v){float a=.5*(sqrt(3.)-1.);ivec2 f=ivec2(floor(v+(v.x+v.y)*a));float x=(3.-sqrt(3.))/6.;v-=f-(f.x+f.y)*x;ivec2 n=v.x>v.y?ivec2(1,0):ivec2(0,1);vec2 m[3]=vec2[3](v,v-n+x,v-1.+2.*x);ivec3 l=ivec3(f.x)+ivec3(0,n.x,1),d=ivec3(f.y)+ivec3(0,n.y,1);float r=0;for(uint y=0;y<3;y++){float s=max(0,.5-m[y].x*m[y].x-m[y].y*m[y].y);s*=s;uint p=t(l[y]+t(d[y]))%12;r+=s*s*dot(i[p].xy,m[y]);}return 70.*r;}float u(vec3 v){float a=1./3.,x=1./6.;ivec3 f=ivec3(floor(v+(v.x+v.y+v.z)*a));v-=f-(f.x+f.y+f.z)*x;vec3 m=step(v.yzx,v);ivec3 n=ivec3(min(m,(1.-m).zxy)),y=ivec3(max(m,(1.-m).zxy));vec3 d[4]=vec3[4](v,v-n+x,v-y+2.*x,v-1.+3.*x);int l[4]=int[4](f.x,f.x+n.x,f.x+y.x,f.x+1),u[4]=int[4](f.y,f.y+n.y,f.y+y.y,f.y+1),s[4]=int[4](f.z,f.z+n.z,f.z+y.z,f.z+1);float r=0;for(uint p=0;p<4;p++){float e=max(0.,.6-d[p].x*d[p].x-d[p].y*d[p].y-d[p].z*d[p].z);e*=e;uint c=t(l[p]+t(u[p]+t(s[p])))%12;r+=e*e*dot(i[c],d[p]);}return 32.*r;}float h(vec2 v){float f=0.;for(int y=0;y<3;y++)f+=exp2(-y)*e(v),v*=2.;return f/1.75;}float y(vec3 v){float f=0.;for(int y=0;y<3;y++)f+=exp2(-y)*e(v),v*=2.;return f/1.75;}float b(vec2 v){float f=0.;for(int y=0;y<3;y++)f+=exp2(-y)*u(v),v*=2.;return f/1.75;}float o(vec3 v){float f=0.;for(int y=0;y<3;y++)f+=exp2(-y)*u(v),v*=2.;return f/1.75;}
#line 2"quat_rotate"
void b(inout vec3 v,vec4 f){vec3 y=2*cross(f.xyz,v);v+=f.w*y+cross(f.xyz,y);}
#line 4"camera"
layout((location=67))uniform vec3 z;layout((location=68))uniform vec4 a;layout((location=69))uniform float g;layout((location=70))uniform float F;float C=g/F;vec3 c(vec2 v,out float y){vec3 a=vec3((v-.5*f)/f.x,g/F);y=length(a.xz);a=normalize(a);return a;}vec3 b(){vec2 v=vec2(u(vec2(l*x,23)),u(vec2(l*x,283)))*m;vec3 a=c(gl_FragCoord.xy+v*f,C);a.z=-a.z;b(a,a);return a;}float q(float v){return.5*v/(C*f.x);}
#line 2"helper"
const float L=3.14159,D=6.28319,Z=2.71828,Y=1.61803,X=1000.,W=1./0.;float V(vec2 v){return min(v.x,v.y);}float U(vec3 v){return min(min(v.x,v.y),v.z);}float T(vec2 v){return max(v.x,v.y);}float S(vec3 v){return max(max(v.x,v.y),v.z);}float S(float v,float f,float a){return min(min(v,f),a);}float S(float v,float f,float a,float y){return min(min(min(v,f),a),y);}float T(float v,float f,float a){return max(max(v,f),a);}float T(float v,float f,float a,float y){return max(max(max(v,f),a),y);}float R(vec2 v){return v.x+v.y;}float Q(vec3 v){return v.x+v.y+v.z;}float P(vec2 v){return v.x*v.y;}float O(vec3 v){return v.x*v.y*v.z;}float N(float v){return v*v;}vec2 M(vec2 v){return v*v;}vec3 K(vec3 v){return v*v;}float J(float v){return 1./v;}vec2 I(vec2 v){return 1./v;}vec3 H(vec3 v){return 1./v;}float H(vec2 v,float f){return pow(Q(pow(abs(v),vec2(f))),1./f);}float I(vec3 v,float f){return pow(Q(pow(abs(v),vec3(f))),1./f);}float G(float v){return clamp(v,0.,1.);}vec2 E(vec2 v){return clamp(v,0.,1.);}vec3 B(vec3 v){return clamp(v,0.,1.);}float B(float v,float f,float a){return clamp((a-v)/(f-v),0.,1.);}float E(float v,float f,float a){float m=clamp((a-v)/(f-v),0.,1.);return m*m*m*(m*(m*6.-15.)+10.);}float B(vec2 v,vec2 f){return max(0.,dot(v,f));}float E(vec3 v,vec3 f){return max(0.,dot(v,f));}float A(float v){return v<0.?-1.:1.;}vec2 k(vec2 v){return vec2(v.x<0.?-1.:1.,v.y<0.?-1.:1.);}vec3 j(vec3 v){return vec3(v.x<0.?-1.:1.,v.y<0.?-1.:1.,v.z<0.?-1.:1.);}vec2 ab(float v){return vec2(cos(v),sin(v));}vec3 A(float v,float f){float a=cos(f),y=sin(v),m=sin(f),x=cos(v);return vec3(m*x,a,m*y);}float A(float v,float f,float a){if(a>v)return a;float m=2.*f-v,y=2.*v-3.*f,x=a/v;return(m*x+y)*x*x+f;}float G(float v,float f){float a=v*f;return a*exp(1.-a);}float G(float v,float f,float a){return a=abs(a-v),a/=f,1.-smoothstep(0.,1.,a);}float H(float v,float f,float a){return exp(-v*pow(a,f));}float J(float v,float f){return pow(4.*f*(1.-f),v);}float I(float v,float f,float a){float m=pow(v+f,v+f)/(pow(v,v)*pow(f,f));return m*pow(a,v)*pow(1.-a,f);}float J(float v,float f,float a){return pow(a,v)*pow(1.-a,f);}float ac(vec3 v){return dot(v,vec3(.2126,.7152,.0722));}vec3 ad(vec3 v){vec4 f=vec4(0.,-1./3.,2./3.,-1.),a=mix(vec4(v.zy,f.wz),vec4(v.yz,f.xy),step(v.z,v.y)),m=mix(vec4(a.xyw,v.x),vec4(v.x,a.yzx),step(a.x,v.x));float y=m.x-min(m.w,m.y),x=1e-10;return vec3(abs(m.z+(m.w-m.y)/(6.*y+x)),y/(m.x+x),m.x);}vec3 ae(vec3 v){vec4 f=vec4(1.,2./3.,1./3.,3.);vec3 a=abs(fract(v.xxx+f.xyz)*6.-f.www);return v.z*mix(f.xxx,clamp(a-f.xxx,0.,1.),v.y);}
#line 6
layout((binding=8)uniform sampler2D depth;layout((location=0))out float af;int ag=10;float ah=.03,ai=2;layout((location=71))uniform float aj;layout((location=72))uniform float ak;layout((location=73))uniform float al;layout((location=74))uniform float am;layout((location=75))uniform bool an;vec2 K(int v,float f){float a=D/ak*(v+f);return vec2(cos(a),sin(a));}vec3 ao(vec2 v){float a=textureLod(depth,v,0).x,y;return a*c(v*(f-1)+.5,y);}vec2 ap(vec2 v){return v;vec2 a=f-1;return round(v*a)/a;}float A(vec2 v,vec3 a,vec3 f,vec3 m,inout float y){vec3 n=ao(v),x=n-a;float l=length(x);if(dot(m,x)<0)return am;float i=dot(f,x)/l,d=max(i-y,0);y=max(i,y);float p=1-K(B(l/ai));return d*p;}float A(vec2 v,vec2 a,float y,vec2 x,vec3 m,vec3 l,int i){vec2 n=a/f;vec3 r=ao(v+n)-m;r-=dot(l,r)*l;vec2 s=ap(a*x/(i-1)),z=mix(n,s,y),d=ap(v+z);float p=ah,u=0;for(int c=0;c<i;c++)u+=A(d,m,l,r,p),d+=s;return u;}void main(){if(an){af=1;return;}float a=textureLod(depth,v,0).x,y;vec3 m=a*c(gl_FragCoord.xy,y),x=normalize(cross(dFdy(m),dFdx(m)));float n=e(gl_FragCoord.xy+3827.5)*.5,z=e(gl_FragCoord.xy+827.5)*.5+.5;vec2 s=aj*y/a*vec2(1,f.y/f.x);float l=s.x*f.x,r=0;if(l>=1){int d=min(ag,int(l));for(int i=0;i<ak;i++){vec2 p=K(i,n);r+=A(v,p,z,s,m,x,d);}r*=al/ak;}float i=1-B(r);af=i;};
#endif
