#ifndef ao_blend_H
#define ao_blend_H
const char ao_blend_source[] =R"shader_source(#version 430
)shader_source"
R"shader_source(in vec2 f;layout(location=0)uniform vec2 m;layout(location=66)uniform float v;
)shader_source"
R"shader_source(#line 2"helper"
)shader_source"
R"shader_source(const float c=3.14159,n=6.28319,s=2.71828,d=1.61803,g=1000.,t=1./0.;float p(vec2 f){return min(f.x,f.y);}float x(vec3 f){return min(min(f.x,f.y),f.z);}float w(vec2 f){return max(f.x,f.y);}float e(vec3 f){return max(max(f.x,f.y),f.z);}float e(float v,float f,float m){return min(min(v,f),m);}float e(float v,float f,float m,float y){return min(min(min(v,f),m),y);}float p(float v,float f,float m){return max(max(v,f),m);}float p(float v,float f,float m,float y){return max(max(max(v,f),m),y);}float o(vec2 f){return f.x+f.y;}float a(vec3 f){return f.x+f.y+f.z;}float l(vec2 f){return f.x*f.y;}float r(vec3 f){return f.x*f.y*f.z;}float u(float f){return f*f;}vec2 i(vec2 f){return f*f;}vec3 y(vec3 f){return f*f;}float z(float f){return 1./f;}vec2 b(vec2 f){return 1./f;}vec3 L(vec3 f){return 1./f;}float L(vec2 f,float v){return pow(a(pow(abs(f),vec2(v))),1./v);}float a(vec3 f,float v){return pow(a(pow(abs(f),vec3(v))),1./v);}float D(float f){return clamp(f,0.,1.);}vec2 h(vec2 f){return clamp(f,0.,1.);}vec3 Z(vec3 f){return clamp(f,0.,1.);}float D(float f,float v,float m){return clamp((m-f)/(v-f),0.,1.);}float L(float f,float v,float m){float p=clamp((m-f)/(v-f),0.,1.);return p*p*p*(p*(p*6.-15.)+10.);}float D(vec2 f,vec2 m){return max(0.,dot(f,m));}float Z(vec3 f,vec3 m){return max(0.,dot(f,m));}float Y(float f){return f<0.?-1.:1.;}vec2 X(vec2 f){return vec2(f.x<0.?-1.:1.,f.y<0.?-1.:1.);}vec3 W(vec3 f){return vec3(f.x<0.?-1.:1.,f.y<0.?-1.:1.,f.z<0.?-1.:1.);}vec2 V(float f){return vec2(cos(f),sin(f));}vec3 V(float f,float v){float m=cos(v),y=sin(f),p=sin(v),x=cos(f);return vec3(p*x,m,p*y);}float V(float f,float v,float m){if(m>f)return m;float p=2.*v-f,y=2.*f-3.*v,x=m/f;return(p*x+y)*x*x+v;}float W(float f,float m){float v=f*m;return v*exp(1.-v);}float W(float f,float v,float m){return m=abs(m-f),m/=v,1.-smoothstep(0.,1.,m);}float X(float f,float m,float v){return exp(-f*pow(v,m));}float X(float f,float m){return pow(4.*m*(1.-m),f);}float Y(float f,float v,float m){float p=pow(f+v,f+v)/(pow(f,f)*pow(v,v));return p*pow(m,f)*pow(1.-m,v);}float Z(float f,float m,float v){return pow(v,f)*pow(1.-v,m);}float U(vec3 f){return dot(f,vec3(.2126,.7152,.0722));}vec3 T(vec3 f){vec4 m=vec4(0.,-1./3.,2./3.,-1.),v=mix(vec4(f.zy,m.wz),vec4(f.yz,m.xy),step(f.z,f.y)),p=mix(vec4(v.xyw,f.x),vec4(f.x,v.yzx),step(v.x,f.x));float x=p.x-min(p.w,p.y),y=1e-10;return vec3(abs(p.z+(p.w-p.y)/(6.*x+y)),x/(p.x+y),p.x);}vec3 S(vec3 f){vec4 v=vec4(1.,2./3.,1./3.,3.);vec3 m=abs(fract(f.xxx+v.xyz)*6.-v.www);return f.z*mix(v.xxx,clamp(m-v.xxx,0.,1.),f.y);}
)shader_source"
R"shader_source(#line 4
)shader_source"
R"shader_source(layout(binding=11)uniform sampler2D R;layout(binding=12)uniform sampler2D Q;layout(location=0)out vec3 P;void main(){vec3 m=textureLod(Q,f,0).xyz;float v=textureLod(R,f,0).x;P=m*v;}
)shader_source";
#endif
