#ifndef ao_blur_v_H
#define ao_blur_v_H
const char ao_blur_v_source[] =R"shader_source(#version 430
)shader_source"
R"shader_source(layout(location=76)uniform float y;layout(location=77)uniform float x;in vec2 f;layout(location=0)uniform vec2 m;layout(location=66)uniform float v;vec2 p=vec2(0,1);
)shader_source"
R"shader_source(#line 2"helper"
)shader_source"
R"shader_source(const float n=3.14159,s=6.28319,d=2.71828,g=1.61803,c=1000.,t=1./0.;float w(vec2 f){return min(f.x,f.y);}float e(vec3 f){return min(min(f.x,f.y),f.z);}float r(vec2 f){return max(f.x,f.y);}float o(vec3 f){return max(max(f.x,f.y),f.z);}float e(float f,float x,float v){return min(min(f,x),v);}float e(float f,float x,float v,float m){return min(min(min(f,x),v),m);}float o(float f,float x,float v){return max(max(f,x),v);}float o(float f,float x,float v,float m){return max(max(max(f,x),v),m);}float a(vec2 f){return f.x+f.y;}float l(vec3 f){return f.x+f.y+f.z;}float u(vec2 f){return f.x*f.y;}float i(vec3 f){return f.x*f.y*f.z;}float z(float f){return f*f;}vec2 b(vec2 f){return f*f;}vec3 L(vec3 f){return f*f;}float D(float f){return 1./f;}vec2 h(vec2 f){return 1./f;}vec3 Z(vec3 f){return 1./f;}float D(vec2 f,float v){return pow(l(pow(abs(f),vec2(v))),1./v);}float L(vec3 f,float v){return pow(l(pow(abs(f),vec3(v))),1./v);}float Y(float f){return clamp(f,0.,1.);}vec2 X(vec2 f){return clamp(f,0.,1.);}vec3 W(vec3 f){return clamp(f,0.,1.);}float D(float f,float v,float m){return clamp((m-f)/(v-f),0.,1.);}float L(float f,float v,float m){float p=clamp((m-f)/(v-f),0.,1.);return p*p*p*(p*(p*6.-15.)+10.);}float W(vec2 f,vec2 v){return max(0.,dot(f,v));}float X(vec3 f,vec3 v){return max(0.,dot(f,v));}float V(float f){return f<0.?-1.:1.;}vec2 U(vec2 f){return vec2(f.x<0.?-1.:1.,f.y<0.?-1.:1.);}vec3 T(vec3 f){return vec3(f.x<0.?-1.:1.,f.y<0.?-1.:1.,f.z<0.?-1.:1.);}vec2 S(float f){return vec2(cos(f),sin(f));}vec3 S(float f,float v){float x=cos(v),y=sin(f),m=sin(v),p=cos(f);return vec3(m*p,x,m*y);}float S(float f,float x,float v){if(v>f)return v;float m=2.*x-f,y=2.*f-3.*x,p=v/f;return(m*p+y)*p*p+x;}float T(float f,float v){float m=f*v;return m*exp(1.-m);}float T(float f,float v,float m){return m=abs(m-f),m/=v,1.-smoothstep(0.,1.,m);}float U(float f,float v,float m){return exp(-f*pow(m,v));}float U(float f,float v){return pow(4.*v*(1.-v),f);}float V(float f,float v,float m){float p=pow(f+v,f+v)/(pow(f,f)*pow(v,v));return p*pow(m,f)*pow(1.-m,v);}float W(float f,float v,float m){return pow(m,f)*pow(1.-m,v);}float R(vec3 f){return dot(f,vec3(.2126,.7152,.0722));}vec3 Q(vec3 f){vec4 v=vec4(0.,-1./3.,2./3.,-1.),m=mix(vec4(f.zy,v.wz),vec4(f.yz,v.xy),step(f.z,f.y)),p=mix(vec4(m.xyw,f.x),vec4(f.x,m.yzx),step(m.x,f.x));float x=p.x-min(p.w,p.y),y=1e-10;return vec3(abs(p.z+(p.w-p.y)/(6.*x+y)),x/(p.x+y),p.x);}vec3 P(vec3 f){vec4 v=vec4(1.,2./3.,1./3.,3.);vec3 m=abs(fract(f.xxx+v.xyz)*6.-v.www);return f.z*mix(v.xxx,clamp(m-v.xxx,0.,1.),f.y);}
)shader_source"
R"shader_source(#line 3
)shader_source"
R"shader_source(layout(binding=10)uniform sampler2D O;layout(binding=8)uniform sampler2D N;layout(location=0)out float M;void main(){float v=textureLod(O,f,0).x,m=textureLod(N,f,0).x;M=v;int c=9;vec2 r=vec2(0),n=1./m;float z=c/3;for(int l=-c;l<=c;l++){vec2 s=f+l*n*p;float a=textureLod(O,s,0).x,d=textureLod(N,s,0).x,t=exp(-.5*L(l/z))+x,g=exp(-.5*L(abs(d-m)/y));r+=t*g*vec2(a,1);}M=r.x/r.y;}
)shader_source";
#endif
